name: diamonds
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.2.0-174.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  cloud_firestore: ^4.9.3
  firebase_core: ^2.17.0
  injectable: ^2.3.2
  get_it: ^7.6.4
  provider: ^6.0.5
  fancy_shimmer_image: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
dev_dependencies:
  injectable_generator: ^2.4.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/common/
